#!/bin/bash
dev_dir="$HOME/Desktop/my_designs" # replase with path where where your projects located
cd "$dev_dir" || exit 1            # check if the folder exists
repos=$(find ./* -type d -name ".git" | cut -d'/' -f2) # finding project folders 

while true; do # While loop allows to run program while user did not make a choice
  echo ""
  echo "You are in: $dev_dir"
  echo ""
  echo 'Select repo:'
  select repo in $repos "Quit"; # menu for selecting repo
  do
    case $repo in
      "Quit")
        echo Goodbye!
        exit 0
        ;;
      *)
        while true; do # while loop allows you to move through the menu until the user has made a selection, and then returns to the menu after making the selection
          echo ""
          cd "$dev_dir/$repo" || exit 1
          pwd "$dev_dir/$repo"
          echo 'Choose what you want to do in repo :' $repo # menu for selecting avalible commands
          echo '    1) Check git status'
          echo '    2) Update to the latest version'
          echo '    3) Add files (local)'
          echo '    4) Remove files (local)'
          echo '    5) Commit changes (local)'
          echo '    6) Push changes to server'
          echo '    7) Go back'
          echo '    q) Quit'

          read choice

          case $choice in
            1)
              echo "Git status for $repo:"
              git status
              ;;
            2)
              echo "Pulling from $repo..."
              git pull
              ;;
            3)
              while true; do # while loop allows you to move through the menu until the user has made a selection, and then returns to the menu after making the selection
               echo ""
                echo "Choose option:" # sub menu for adding files
                echo '    1) Add separate files (name or path)'
                echo '    2) Add all files'
                echo '    3) Go back'
                echo '    q) Quit'

                read choice_add

                case $choice_add in
                  1)
                    echo 'Input file names or paths (space-separated):'
                    read -r files
                    git add $files
                    ;;
                  2)
                    echo "Adding all files..."
                    git add .
                    ;;
                  3)
                    break
                    ;;
                  q|Q)
                    echo "Goodbye!"
                    exit 0
                    ;;
                  *)
                    echo "Invalid choice. Choose 1, 2, 3, or q."
                    ;;
                esac
              done
              ;;
            4)
              echo "Removing files (local)..."
              echo 'Input file names or paths (space-separated):'
              read -r files_to_remove
              git rm $files_to_remove
              ;;
            5)
              echo 'Committing changes (local)...'
              echo "Enter a commit message:"
              read -r commit_message
              git commit -m "$commit_message"
              ;;
            6)
              echo "Pushing changes to the server..."
              git push
              ;;
            7)
              break
              ;;
            q|Q)
              echo "Goodbye!"
              exit 0
              ;;
            *)
              echo 'Invalid choice. Choose 1, 2, 3, 4, 5, 6, 7, or q.'
              ;;
          esac
        done
        ;;
    esac
   break
  done
done
